export default [
    {name: 'equipment', path: '/equipment'},
    {name: 'equipment.journal', path: '/journal'},
    {name: 'consumables', path: '/consumables'},
    {name: 'vendor', path: '/vendor'},
    {name: 'model', path: '/model'},
    {name: 'hardwareType', path: '/hardware-type'},
    {name: 'state', path: '/state'},
    {name: 'location', path: '/location'},
    {name: 'location.tag', path: '/tag'},
    {name: 'contract', path: '/contract'},
    {name: 'provider', path: '/provider'},
    {name: 'user', path: '/user'},
    {name: 'group', path: '/group'},
    {name: 'consignment', path: '/consignment'},
    {name: 'consignment.sent', path: '/sent'},
    {name: 'consignment.accepted', path: '/accepted'},
    {name: 'reports', path: '/reports'},
];